package com.greatorator.tolkienmobs.datagen;

import com.greatorator.tolkienmobs.datagen.helpers.TolkienLangHelperUS;
import com.greatorator.tolkienmobs.init.TolkienBlocks;
import com.greatorator.tolkienmobs.init.TolkienEntities;
import com.greatorator.tolkienmobs.init.TolkienItems;
import net.minecraft.data.PackOutput;

import javax.annotation.Nonnull;
import java.util.HashMap;
import java.util.Map;

public class TolkienLangProviderUS extends TolkienLangHelperUS {
    public static final Map<String, String> SUBTITLE_GENERATOR = new HashMap<>();

    public TolkienLangProviderUS(PackOutput output) {
        super(output);
    }

    @Override
    protected void addTranslations() {
        this.add("itemgroup.tolkienmobs.deco", "托尔金工艺：建筑方块");
            this.addItem(TolkienItems.CREBAIN_FEATHER, "克拉班的羽毛");
            this.addItem(TolkienItems.BIRD_FEATHER, "鸟羽");
            this.addItem(TolkienItems.MUMAKIL_LEATHER, "硬化皮革");
            this.addItem(TolkienItems.MONSTER_FUR, "捆扎毛皮");
            this.addItem(TolkienItems.BOTTLE_FANCY, "精美瓶子");
            this.addItem(TolkienItems.FOOD_HONEY, "蜜蜂蜂窝");
            this.addItem(TolkienItems.MONSTER_FLESH, "腐臭肉块");
            this.addItem(TolkienItems.INSECT, "青蛙饵料");
            this.addItem(TolkienItems.GOLDEN_INSECT, "精美青蛙饵料");
            this.addItem(TolkienItems.TREE_ACORN, "橡果");
            this.addItem(TolkienItems.GOLDEN_TREE_ACORN, "金橡果");
            this.addItem(TolkienItems.GOLEM_STONE, "魔像石");
            this.addItem(TolkienItems.GOLEM_STONE_EARTH, "§2土§r之魔像石");
            this.addItem(TolkienItems.GOLEM_STONE_AIR, "§e气§r之魔像石");
            this.addItem(TolkienItems.GOLEM_STONE_FIRE, "§4火§r之魔像石");
            this.addItem(TolkienItems.GOLEM_STONE_WATER, "§9水§r之魔像石");
            this.addItemWithLore(TolkienItems.GOLEM_STONE_SUMMON.get(), "§b秘银§r魔像石", "用来召唤传奇魔像的远古神器");
            this.addItemWithLore(TolkienItems.ITEM_BACKPACK_UPGRADE_BASE.get(), "背包升级 - 基础", "用于制造背包升级的基础配件");
            this.addItemWithLore(TolkienItems.ITEM_BACKPACK_UPGRADE_SIZE.get(), "背包升级 - 尺寸 - 等级1", "增加背包的存储容量（+27格，可升级最大值-1）");
            this.addItemWithLore(TolkienItems.ITEM_BACKPACK_UPGRADE_SIZE_2.get(), "背包升级 - 尺寸 - 等级2", "进一步增加背包的存储容量（+27格，可升级最大值-1）");
            this.addItemWithLore(TolkienItems.ITEM_BACKPACK_UPGRADE_FLUID.get(), "背包升级 - 流体储存 - 等级1", "允许携带8桶流体（可升级最大值-1）");
            this.addItemWithLore(TolkienItems.ITEM_BACKPACK_UPGRADE_FLUID_2.get(), "背包升级 - 流体储存 - 等级2", "允许携带16桶流体（可升级最大值-1）");
            this.addItemWithLore(TolkienItems.ITEM_BACKPACK_UPGRADE_FLUID_3.get(), "背包升级 - 流体储存 - 等级3", "允许携带32桶流体（可升级最大值-1）");
            this.addItemWithLore(TolkienItems.ITEM_BACKPACK_UPGRADE_FLUID_4.get(), "背包升级 - 流体储存 - 等级4", "允许携带128桶流体（可升级最大值-1）");
            this.addItemWithLore(TolkienItems.ITEM_BACKPACK_UPGRADE_FLUID_5.get(), "背包升级 - 流体储存 - 等级5", "允许存储的流体为无限量（可升级最大值-1）");
            this.addItemWithLore(TolkienItems.ITEM_BACKPACK_UPGRADE_CRAFTING.get(), "背包升级 - 合成", "允许随处合成（可升级最大值-1）");
            this.addItemWithLore(TolkienItems.ITEM_BACKPACK_UPGRADE_SLEEPING.get(), "背包升级 - 睡袋", "随身携带睡袋（可升级最大值-1）");
            this.addItemWithLore(TolkienItems.ITEM_BACKPACK_UPGRADE_CAMPFIRE.get(), "背包升级 - 营火", "快速使用营火（可升级最大值-1）");
            this.addItem(TolkienItems.TEMPLATE_MITHRIL, "锻造模板：秘银");
            this.addItem(TolkienItems.TEMPLATE_MORGULIRON, "锻造模板：魔古尔铁");
            this.addItem(TolkienItems.TEMPLATE_AMMOLITE, "锻造模板：斑彩石");
        this.add("itemgroup.tolkienmobs.natural", "托尔金工艺：自然方块");
            this.addItem(TolkienItems.PIPEWEED_SEEDS, "烟斗草种子");
            this.addItem(TolkienItems.PIPEWEED_ITEM, "烟斗草");
            this.addFlowerBlock(TolkienBlocks.FLOWER_SIMBELMYNE.get(), "辛贝穆奈", "辛贝穆奈");
            this.addFlowerBlock(TolkienBlocks.FLOWER_MIRKWOOD.get(), "色瑞刚", "黑森林");
            this.addFlowerBlock(TolkienBlocks.FLOWER_ALFIRIN.get(), "阿尔费琳", "阿尔费琳");
            this.addFlowerBlock(TolkienBlocks.FLOWER_ATHELAS.get(), "王叶草", "阿塞拉斯");
            this.addFlowerBlock(TolkienBlocks.FLOWER_NIPHREDIL.get(), "妮芙瑞迪尔", "妮芙瑞迪尔");
            this.addFlowerBlock(TolkienBlocks.FLOWER_SWAMPMILKWEED.get(), "绞架草", "沼泽马利筋");
            this.addFlowerBlock(TolkienBlocks.FLOWER_LILLYOFTHEVALLEY.get(), "铃兰", "山谷百合");
            this.addFlowerBlock(TolkienBlocks.FLOWER_ELANOR.get(), "埃拉诺", "埃拉诺");
            this.addFlowerBlock(TolkienBlocks.FLOWER_AEGLOS.get(), "雪棘", "艾格洛斯");
            this.addFlowerBlock(TolkienBlocks.FLOWER_LISSUIN.get(), "利斯苏因", "利斯苏因");
            this.addFlowerBlock(TolkienBlocks.FLOWER_MALLOS.get(), "瑁洛斯", "瑁洛斯");
            this.addFlowerBlock(TolkienBlocks.FLOWER_BRAMBLES.get(), "魔多荆棘", "荆棘");
            this.addFlowerBlock(TolkienBlocks.MUSHROOM_BLOOM_DECAY.get(), "腐烂之花", "蘑菇开花腐烂");
            this.addFlowerBlock(TolkienBlocks.MUSHROOM_DECAY_BLOOM.get(), "腐烂之花", "蘑菇腐烂开花");
            this.addBlock(TolkienBlocks.BLOCK_DECAY_BLOOM, "腐烂花方块");
            this.addBlock(TolkienBlocks.LIGHTNINGBUG_BLOCK, "萤火虫");
            this.addBlock(TolkienBlocks.LOCUST_BLOCK, "蝗虫");
            this.addBlock(TolkienBlocks.BLOCK_HALLOWED, "神圣土地");
            this.addBlock(TolkienBlocks.STONE_PATH, "石头路");
            this.addBlock(TolkienBlocks.WALL_DECAY_BLOOM, "蘑菇墙 - 腐烂之花");
            this.addBlock(TolkienBlocks.WALL_MUSHROOM_RED, "蘑菇墙 - 红色");
            this.addBlock(TolkienBlocks.WALL_MUSHROOM_BROWN, "蘑菇墙 - 棕色");
            this.addBlock(TolkienBlocks.LIVING_ROOTS, "活根");
            this.addBlockWithLore(TolkienBlocks.PLACARD.get(), "国家标识", "按住Shift时右击告示牌以转换类型");
            this.addBlock(TolkienBlocks.ROCKPILE, "石堆");
            this.addBlock(TolkienBlocks.MOSS_PATCH, "苔藓地");
            this.addBlock(TolkienBlocks.CLOVER_PATCH, "幸运草地");
        this.add("itemgroup.tolkienmobs.food", "托尔金工艺：食物与饮料");
            this.addItem(TolkienItems.LEMBAS, "兰巴斯");
            this.addItem(TolkienItems.CRAM, "克拉姆");
            this.addItem(TolkienItems.HONEY_CAKE, "蜂蜜蛋糕");
            this.addItem(TolkienItems.BRAMBLES_BERRY, "荆棘浆果");
            this.addItem(TolkienItems.MIRUVOR, "米茹沃");
            this.addItem(TolkienItems.GROG, "格罗格酒");
            this.addItem(TolkienItems.DRINK_ELF_FLEETFOOT, "精灵祝福饮料");
            this.addItem(TolkienItems.DRINK_ELF_VITALITY, "活力饮料");
            this.addItem(TolkienItems.DRINK_ERU_BLESSING, "一如·伊露维塔祝福饮料");
            this.addItem(TolkienItems.DRINK_ENT_DRAUGHT, "恩特饮料");
            this.addItem(TolkienItems.DRINK_PERSONAL_BLACKSMITH, "随身铁匠");
        this.add("itemgroup.tolkienmobs.quest", "托尔金工艺：基础物品");
            this.addItemWithLore(TolkienItems.ITEM_BERYL.get(), "§3格罗芬德尔的绿玉§r", "借给你的神奇宝石，帮助你搜寻敌人的踪迹。");
            this.addItemWithLore(TolkienItems.ITEM_FORTRESSMAP.get(), "§3要塞图纸§r", "看似脆弱，却能完好保存如此之久，令人惊讶！");
            this.addItemWithLore(TolkienItems.ITEM_WATCHERHEART.get(), "§5石心§r", "这颗心脏具有令人恐惧与不安的能量");
            this.addItemWithLore(TolkienItems.ITEM_WATCHERHEART_CRACKED.get(), "§5监视者的心脏§r", "这颗心看起来破旧不堪");
            this.addItemWithLore(TolkienItems.ITEM_KEYSTONE.get(), "§3钥匙石§r", "几乎被遗忘，但却是打开某个秘密入口的“钥匙”。");
            this.addItemWithLore(TolkienItems.ITEM_DARKSADDLE.get(), "§9黑骏马的缰绳§r", "从一匹邪恶鞍马的尸体上取下");
            this.addItemWithLore(TolkienItems.ITEM_ARTIFACT.get(), "§6失落神器§r", "这个物体散发出一股黑暗的气息");
            this.addItemWithLore(TolkienItems.ITEM_BLANKPAPER.get(), "§5手稿书页§r", "一份手稿的遗失书页");
            this.addItemWithLore(TolkienItems.ITEM_FANCYARMOR.get(), "§5克罗米斯的盔甲§r§2（已修复）§r", "克罗米斯的盔甲修复后，看起来令人惊叹不已。");
            this.addItemWithLore(TolkienItems.ITEM_FANCYCLOTH.get(), "§2精美布料§r", "用于装饰的精美布料");
            this.addItemWithLore(TolkienItems.ITEM_FANCYHAMMER.get(), "§9瑟罗尔之锤§r", "专门设计用于锻造秘银的锤子");
            this.addItemWithLore(TolkienItems.ITEM_FANCYHELM.get(), "精美头盔", "");
            this.addItemWithLore(TolkienItems.ITEM_FANCYKEY.get(), "§3墨瑞亚矿坑的钥匙§r", "埃尔苏利用你收集的物品而制作出的钥匙。");
            this.addItemWithLore(TolkienItems.ITEM_FANCYPICK.get(), "精美镐", "");
            this.addItemWithLore(TolkienItems.ITEM_FANCYSHIELD.get(), "精美盾牌", "");
            this.addItemWithLore(TolkienItems.ITEM_FANCYSHIELD2.get(), "§5克罗米斯的盾牌§r§2（已修复）§r", "这块盾牌虽然来历不明，但是属于克罗米斯。");
            this.addItemWithLore(TolkienItems.ITEM_FANCYSWORD.get(), "§5克罗米斯的剑§r§2（已修复）§r", "铁匠将这把剑锻造得十分出色");
            this.addItemWithLore(TolkienItems.ITEM_FANCYSWORD2.get(), "§4使徒之剑§r", "复仇的希望");
            this.addItemWithLore(TolkienItems.ITEM_LETTER.get(), "§6瑟尔丹的信§r", "来自瑟尔丹的信，关于德鲁哈拉。");
            this.addItemWithLore(TolkienItems.ITEM_SCROLL.get(), "§5灰烬卷轴§r", "一个破旧的卷轴，上面写满了小符文。");
            this.addItemWithLore(TolkienItems.ITEM_SCROLL2.get(), "§5译文卷轴§r", "埃尔隆德翻译得到的一个卷轴，上面有如何进入墨瑞亚矿坑的说明。");
            this.addItemWithLore(TolkienItems.ITEM_SPECIALFLOWER.get(), "§2女巫啤酒花§r", "酿酒师特别喜欢用的浓香原材料");
            this.addItemWithLore(TolkienItems.ITEM_STORYBOOK.get(), "§3霍比特人的故事§r", "自从比尔博在生日那天失踪后，一个霍比特人讲述的故事。");
            this.addItemWithLore(TolkienItems.ITEM_STORYBOOK2.get(), "§6比尔博的故事§r", "老头儿甘姆吉为比尔博的生日准备的礼物");
            this.addItemWithLore(TolkienItems.ITEM_STORYBOOK3.get(), "§3佩图尼亚的手稿§r", "一位年轻霍比特人的冒险日志");
            this.addItemWithLore(TolkienItems.ITEM_STORYBOOK4.get(), "§2古代巨著§r", "这本书看起来已经破旧不堪了");
            this.addItemWithLore(TolkienItems.ITEM_WORNARMOR.get(), "§5克罗米斯的盔甲§r", "克罗米斯被囚禁时，身上被偷走的物品之一。");
            this.addItemWithLore(TolkienItems.ITEM_WORNHELM.get(), "§5破碎的头盔§r", "梭恩鲁姆希望得到修复的物品");
            this.addItemWithLore(TolkienItems.ITEM_WORNKEY.get(), "§5强盗的钥匙§r", "在一位强盗头目的尸体上发现的破损钥匙");
            this.addItemWithLore(TolkienItems.ITEM_WORNPICK.get(), "§5破旧的镐§r", "梭恩鲁姆希望得到修复的物品");
            this.addItemWithLore(TolkienItems.ITEM_WORNSHIELD.get(), "§5损坏的盾牌§r", "梭恩鲁姆希望得到修复的物品");
            this.addItemWithLore(TolkienItems.ITEM_WORNSHIELD2.get(), "§5克罗米斯的盾牌§r", "克罗米斯被囚禁时，身上被偷走的物品之一。");
            this.addItemWithLore(TolkienItems.ITEM_WORNSWORD.get(), "§5克罗米斯的剑§r", "克罗米斯被囚禁时，身上被偷走的物品之一。");
            this.addItemWithLore(TolkienItems.ITEM_WOVENBASKET.get(), "§2编织篮§r", "用来表示敬意的编织篮");
            this.addItemWithLore(TolkienItems.ITEM_WRITTENPAPER.get(), "§5雕像的符文拓印§r", "卡扎督姆附近监视者基座上符文的木炭拓印");
            this.addItemWithLore(TolkienItems.ITEM_PUNGENTHERB.get(), "§4刺鼻的草药§r", "用于制作强效药剂的草药");
            this.addItemWithLore(TolkienItems.ITEM_LOCKPICK.get(), "开锁工具", "用于开门的物品");
            this.addItemWithLore(TolkienItems.ITEM_BROKENSWORD.get(), "§5剑柄§r", "矮人之剑仅存的残骸。");
            this.addItemWithLore(TolkienItems.ITEM_REFORGEDSWORD.get(), "重铸的剑", "杰出的矮人作品");
            this.addItemWithLore(TolkienItems.ITEM_MAGIC_CLOTH.get(), "§5特殊魔法布袋§r", "精美精灵布料做成的袋子");
            this.addItemWithLore(TolkienItems.ITEM_KEYFRAGMENT.get(), "钥匙碎片", "");
            this.addItemWithLore(TolkienItems.ITEM_OILYKEY.get(), "油封钥匙", "");
            this.addItemWithLore(TolkienItems.ITEM_MITHRILNUGGET.get(), "§5比尔博的秘银粒§r", "比尔博从孤山探险中获得的纪念物品");
            this.addItemWithLore(TolkienItems.ITEM_REMAINS.get(), "§2白骨堆§r", "一些可怜不幸者的遗体");
            this.addItemWithLore(TolkienItems.ITEM_RUNE_STONE.get(), "§2远古符文石§r", "这块石头蕴藏着非常强大的黑暗魔法");
            this.addItemWithLore(TolkienItems.ITEM_COIN_BRONZE.get(), "青铜币", "64 枚可兑换 1 枚银币");
            this.addItemWithLore(TolkienItems.ITEM_COIN_SILVER.get(), "银币", "64 枚可兑换 1 枚金币");
            this.addItemWithLore(TolkienItems.ITEM_COIN_GOLD.get(), "金币", "64 枚可兑换 1 枚秘银币");
            this.addItemWithLore(TolkienItems.ITEM_COIN_MITHRIL.get(), "秘银币", "非常稀有和珍贵的钱币");
            this.addItemWithLore(TolkienItems.ITEM_DARKSIGIL.get(), "§5黑暗徽章§r", "邪恶爪牙掉落的黑暗符记");
            this.addItemWithLore(TolkienItems.ITEM_FACTIONCOIN.get(), "§3派系硬币§r", "这可用来换取独特的物品");
            this.addItemWithLore(TolkienItems.ITEM_FACTIONTOKEN.get(), "§9派系信物§r", "用它来提高你在派系的地位");
            this.addItemWithLore(TolkienItems.ITEM_CAVECOMPLETE.get(), "§3洞穴通关信物§r", "杀死食人妖的证明");
            this.addItemWithLore(TolkienItems.ITEM_WATCHERCOMPLETE.get(), "§3监视者击杀信物§r", "击败监视者的证明");
            this.addItemWithLore(TolkienItems.ITEM_TOKEN_EASTERN_ALLIANCE.get(), "§4东部联盟代币§r", "你决定与谁结盟的证明");
            this.addItemWithLore(TolkienItems.ITEM_TOKEN_WESTERN_ALLIANCE.get(), "§1西部联盟代币§r", "你决定与谁结盟的证明");
            this.addItem(TolkienItems.ITEM_EXPERIENCE_ORB, "§2经验§r");
            this.addItemWithInstructions(TolkienItems.BRONZE_KEY.get(), "青铜钥匙", "左键使用: ", "在创造模式按住 Shift键", "鼠标右击以确认/改变钥匙编号");
            this.addItemWithInstructions(TolkienItems.SILVER_KEY.get(), "银钥匙", "左键使用: ", "在创造模式按住 Shift键", "鼠标右击以确认/改变钥匙编号");
            this.addItemWithInstructions(TolkienItems.GOLD_KEY.get(), "金钥匙", "左键使用: ", "在创造模式按住 Shift键", "鼠标右击以确认/改变钥匙编号");
            this.addItemWithInstructions(TolkienItems.MITHRIL_KEY.get(), "秘银钥匙", "左键使用: ", "在创造模式按住 Shift键", "鼠标右击以确认/改变钥匙编号");
            this.addItemWithInstructions(TolkienItems.MASTER_KEY.get(), "主宰钥匙", "左键使用: ", "在创造模式按住 Shift键", "鼠标右击以确认/改变钥匙编号");
        this.add("itemgroup.tolkienmobs.spawn", "托尔金工艺：生物");
        this.add("itemgroup.tolkienmobs.trinket", "托尔金工艺：饰品");
            this.createTrinketSet("ring", "指环");
            this.createTrinketSet("amulet", "护身符");
            this.createTrinketSet("charm", "吊坠");
            this.createTrinketSet("belt", "腰带");
            this.createTrinketSet("glove", "手套");
            this.createTrinketSet("hat", "帽子");
            this.createTrinketSet("cloak", "斗篷");
        this.add("itemgroup.tolkienmobs.tools", "托尔金工艺：工具");
            this.addItem(TolkienItems.COIN_POUCH, "硬币袋");
            this.addItem(TolkienItems.KEY_RING, "钥匙扣");
            this.addItemWithLore(TolkienItems.ITEM_DEV_TOOL.get(), "开发工具", "用于将伪装方块临时重置为默认材质");
            this.addItemWithLore(TolkienItems.ITEM_DEV_DEBUG_TOOL.get(), "开发工具 - 调试", "用于重置某些方块");
            this.addItemWithLore(TolkienItems.ARDA_STAFF.get(), "阿尔达手杖", "按住Shift同时右击传送门框架以激活");
            this.addItemWithLore(TolkienItems.HOBBIT_RING.get(), "霍比特人的丰收戒指", "精灵的礼物，提升耕作能力。");
            this.addItemWithLore(TolkienItems.SWORD_WITCHKING.get(), "§4巫王之剑§r", "在恐惧中铸就，巫王的强大武器。");
            this.addItemWithLore(TolkienItems.SWORD_URUK.get(), "乌鲁克剑", "在艾森加德的地火中锻造而成");
            this.addItemWithLore(TolkienItems.WHIP_FIRE.get(), "§4火焰长鞭§r", "可怕炎魔的主要武器");
            this.addItemWithLore(TolkienItems.CLUB_WOODEN.get(), "食人妖狼牙棒", "深受食人妖喜爱的致命武器");
            this.addItemWithLore(TolkienItems.RING_OF_HOPE.get(), "§5阿格拉尔之环§r", "§6希望在你心中燃烧。§r");
            this.addTools("mithril", "秘银");
            this.addTools("morguliron", "魔古尔铁");
            this.addTools("ammolite", "斑彩石");
            this.addItem(TolkienItems.DWARVEN_HAMMER, "矮人矿锤");
            this.addItem(TolkienItems.HYPE_HORN, "宣传号角");
            this.addItem(TolkienItems.HELMET_MITHRIL, "秘银头盔");
            this.addItem(TolkienItems.CHESTPLATE_MITHRIL, "秘银胸甲");
            this.addItem(TolkienItems.LEGGINGS_MITHRIL, "秘银护腿");
            this.addItem(TolkienItems.BOOTS_MITHRIL, "秘银靴子");
            this.addItem(TolkienItems.MITHRIL_HORSE_ARMOR, "秘银马铠");
            this.addItem(TolkienItems.HELMET_MORGULIRON, "魔古尔铁头盔");
            this.addItem(TolkienItems.CHESTPLATE_MORGULIRON, "魔古尔铁胸甲");
            this.addItem(TolkienItems.LEGGINGS_MORGULIRON, "魔古尔铁护腿");
            this.addItem(TolkienItems.BOOTS_MORGULIRON, "魔古尔铁靴子");
            this.addItem(TolkienItems.MORGULIRON_HORSE_ARMOR, "魔古尔铁马铠");
            this.addItem(TolkienItems.HELMET_AMMOLITE, "斑彩石头盔");
            this.addItem(TolkienItems.CHESTPLATE_AMMOLITE, "斑彩石胸甲");
            this.addItem(TolkienItems.LEGGINGS_AMMOLITE, "斑彩石护腿");
            this.addItem(TolkienItems.BOOTS_AMMOLITE, "斑彩石靴子");
            this.addItem(TolkienItems.AMMOLITE_HORSE_ARMOR, "斑彩石马铠");
            this.addItem(TolkienItems.ELVEN_BOW, "精灵弓");
            this.addItem(TolkienItems.BOULDER, "巨石");
            this.addItem(TolkienItems.FELLBEAST_FIREBALL, "凶恶巨兽火球");
            this.addItem(TolkienItems.URUK_BOW, "乌鲁克弓");
            this.addItem(TolkienItems.GALADHRIM_ARROW, "加拉兹民之箭");
            this.addItem(TolkienItems.UTUMNO_ARROW, "乌图姆诺箭");
            this.addMusicDisc(TolkienItems.RECORD_EREBOR, "SnowShepherd - 在埃瑞博山中闪闪发光的一切");
            this.addMusicDisc(TolkienItems.RECORD_HOBBITS, "Harry Murrell - 令人担忧的霍比特人");
            this.addMusicDisc(TolkienItems.RECORD_MINASTIRITH, "SnowShepherd - 米那斯提力斯的宏伟");
            this.addMusicDisc(TolkienItems.RECORD_MURDERFROG, "SnowShepherd - 杀人蛙的战争");
            this.addMusicDisc(TolkienItems.RECORD_BOMBADIL, "SnowShepherd - 邦巴迪尔的奇思妙想");
            this.addMusicDisc(TolkienItems.RECORD_REDER, "SnowShepherd - Reder的复仇");
            this.addMusicDisc(TolkienItems.RECORD_RIVENDELL, "SnowShepherd - 幽谷的骑手");
            this.addMusicDisc(TolkienItems.RECORD_LOTHLORIEN, "SnowShepherd - 洛丝罗瑞恩之光");
            this.addMusicDisc(TolkienItems.RECORD_WILLOW, "SnowShepherd - 为了一点阴影");
            this.addMusicDisc(TolkienItems.RECORD_FUMBLE, "SnowShepherd - 笨拙的食人妖");
            this.addMusicDisc(TolkienItems.RECORD_EDORAS, "SnowShepherd - 驭马者的家");
            this.addMusicDisc(TolkienItems.RECORD_WBATTLE, "SnowShepherd - Ephalba的国度");
        this.add("itemgroup.tolkienmobs.mats", "托尔金工艺：原材料");
        this.add("itemgroup.tolkienmobs.function", "托尔金工艺：功能方块");
            this.addBlock(TolkienBlocks.TRINKET_TABLE, "饰品桌");
            this.add(TolkienBlocks.FIREPLACE.get(), "壁炉");
            this.add(TolkienBlocks.PIGGYBANK.get(), "猪猪存钱罐");
            this.add(TolkienBlocks.BACKPACK.get(), "冒险者背包");
            this.add(TolkienBlocks.CHAMELEON_BLOCK.get(), "变色方块");
            this.add(TolkienBlocks.KEY_STONE_BLOCK.get(), "伪装的钥匙石方块");
            this.add(TolkienBlocks.CAMO_GLOWSTONE_BLOCK.get(), "伪装的荧石");
            this.add(TolkienBlocks.CAMO_SMOKER_BLOCK.get(), "伪装的发烟器");
            this.add(TolkienBlocks.CAMO_FLUID_BLOCK.get(), "伪装的流体源");
            this.add(TolkienBlocks.CAMO_CHEST_BLOCK.get(), "伪装的箱子");
            this.add(TolkienBlocks.CAMO_SPAWNER_BLOCK.get(), "伪装的刷怪笼");
            this.add(TolkienBlocks.MILESTONE_BLOCK.get(), "快速旅行里程碑");
            this.add(TolkienBlocks.WELL.get(), "水井");
            this.add(TolkienBlocks.LOCKABLE_CHEST_BLOCK.get(), "可上锁的箱子");
            this.add(TolkienBlocks.LOCKABLE_TREASURE_CHEST_BLOCK.get(), "可上锁的宝箱");
            this.add(TolkienBlocks.LOCKABLE_DOUBLE_CHEST_BLOCK.get(), "可上锁的大箱子");
            this.add(TolkienBlocks.LOCKABLE_DOUBLE_TREASURE_CHEST_BLOCK.get(), "可上锁的大宝箱");
            this.addBlock(TolkienBlocks.SILMARIL_LANTERN, "埃兰迪尔之光");
            this.addBlock(TolkienBlocks.ELVEN_LANTERN, "精灵灯笼");
            this.addBlock(TolkienBlocks.MORGUL_LANTERN, "魔古尔灯笼");
            this.addBlock(TolkienBlocks.TORCH_MALLORN, "瑁珑木火把");
            this.addBlock(TolkienBlocks.TORCH_MIRKWOOD, "阴郁木火把");
            this.addBlock(TolkienBlocks.TORCH_CULUMALDA, "库露瑁勒达木火把");
            this.addBlock(TolkienBlocks.TORCH_LEBETHRON, "莱贝斯隆木火把");
            this.addBlock(TolkienBlocks.TORCH_FANGORNOAK, "范贡橡木火把");
            this.addBlock(TolkienBlocks.TORCH_DEADWOOD, "枯萎木火把");
            this.addBlock(TolkienBlocks.TORCH_DWARVEN_MAPLE, "矮人枫木火把");
            this.addBlock(TolkienBlocks.ANCIENT_WATCHER, "远古监视者石像");
            this.addBlock(TolkienBlocks.ANCIENT_DEAD_WATCHER, "损坏的远古监视者石像");

        this.createWoodSet("mallorn", "瑁珑木");
            this.createWoodSet("mirkwood", "黑森林木");
            this.createWoodSet("culumalda", "库露瑁勒达木");
            this.createWoodSet("lebethron", "莱贝斯隆木");
            this.createWoodSet("fangornoak", "范贡橡木");
            this.createWoodSet("deadwood", "枯萎木");
            this.createWoodSet("dwarven_maple", "矮人枫木");
            this.createMetalSet("mithril", "秘银");
            this.createMetalSet("morguliron", "魔古尔铁");

            this.createStoneSet("dwarven_stone", "矮人岩石");
            this.createStoneSet("chiseled_dwarven_stone_bricks", "雕纹矮人岩石砖");
            this.createStoneSet("cobbled_dwarven_stone", "矮人岩圆石");
            this.createStoneSet("mossy_dwarven_stone_bricks", "覆苔矮人鹅卵石");
            this.createStoneSet("mossy_cobbled_dwarven_stone", "覆苔矮人岩石砖");
            this.createStoneSet("cracked_dwarven_stone_bricks", "裂纹矮人岩石");
            this.createStoneSet("dwarven_stone_bricks", "矮人岩石砖");
            this.createStoneSet("smooth_dwarven_stone", "平滑矮人岩石");
            this.createStoneSet("dark_stone", "暗石");
            this.createStoneSet("mossy_cobbled_dark_stone", "覆苔暗鹅卵石");
            this.createStoneSet("mossy_dark_stone_bricks", "覆苔暗石砖");
            this.createStoneSet("chiseled_dark_stone_bricks", "雕纹暗石砖");
            this.createStoneSet("cobbled_dark_stone", "暗石圆石");
            this.createStoneSet("cracked_dark_stone_bricks", "裂纹暗石");
            this.createStoneSet("dark_stone_bricks", "暗石砖");
            this.createStoneSet("smooth_dark_stone", "平滑暗石");
            this.createStoneSet("mountain_stone", "山岩");
            this.createStoneSet("chiseled_mountain_stone_bricks", "雕纹山岩砖");
            this.createStoneSet("cobbled_mountain_stone", "山岩圆石");
            this.createStoneSet("cracked_mountain_stone_bricks", "裂纹山岩");
            this.createStoneSet("mountain_stone_bricks", "山岩砖");
            this.createStoneSet("smooth_mountain_stone", "平滑山岩");
            this.createStoneSet("mossy_cobbled_mountain_stone", "覆苔山卵石");
            this.createStoneSet("mossy_mountain_stone_bricks", "覆苔山岩砖");
            this.createStoneSet("elven_marble", "精灵大理石");
            this.createStoneSet("chiseled_elven_marble_bricks", "雕纹精灵大理石砖");
            this.createStoneSet("cobbled_elven_marble", "精灵大理石圆石");
            this.createStoneSet("cracked_elven_marble_bricks", "裂纹精灵大理石");
            this.createStoneSet("elven_marble_bricks", "精灵大理石砖");
            this.createStoneSet("mossy_elven_marble_bricks", "覆苔精灵大理石砖");
            this.createStoneSet("smooth_elven_marble", "平滑精灵大理石");
            this.createStoneSet("mossy_cobbled_elven_marble", "覆苔精灵鹅卵大理石");
            this.createStoneSet("iron_stone", "铁丘陵石");
            this.createStoneSet("chiseled_iron_stone_bricks", "錾制铁丘陵石砖");
            this.createStoneSet("cobbled_iron_stone", "铁丘陵鹅卵石");
            this.createStoneSet("cracked_iron_stone_bricks", "裂纹铁丘陵石");
            this.createStoneSet("iron_stone_bricks", "铁丘陵石砖");
            this.createStoneSet("mossy_iron_stone_bricks", "覆苔铁丘陵石砖");
            this.createStoneSet("smooth_iron_stone", "平滑铁丘陵石");
            this.createStoneSet("mossy_cobbled_iron_stone", "覆苔铁丘陵鹅卵石");
            this.createStoneSet("angainor", "安盖诺尔石");
            this.createStoneSet("chiseled_angainor_bricks", "錾制安盖诺尔石砖");
            this.createStoneSet("cobbled_angainor", "安盖诺尔鹅卵石");
            this.createStoneSet("cracked_angainor_bricks", "裂纹安盖诺尔石");
            this.createStoneSet("angainor_bricks", "安盖诺尔石砖");
            this.createStoneSet("mossy_angainor_bricks", "覆苔安盖诺尔石砖");
            this.createStoneSet("smooth_angainor", "平滑安盖诺尔石");
            this.createStoneSet("mossy_cobbled_angainor", "覆苔安盖诺尔鹅卵石");

            this.createGemSet("ammolite", "斑彩石");

            this.addBlock(TolkienBlocks.DOOR_DURIN, "都林之门");

            this.addBlockWithLore(TolkienBlocks.SLEEPING_BAG_BLUE.get(), "蓝色睡袋", "§c不会§r重置出生点。");
            this.addBlockWithLore(TolkienBlocks.SLEEPING_BAG_RED.get(), "红色睡袋", "§c不会§r重置出生点。");
            this.addBlockWithLore(TolkienBlocks.SLEEPING_BAG_BLACK.get(), "黑色睡袋", "§c不会§r重置出生点。");
            this.addBlockWithLore(TolkienBlocks.SLEEPING_BAG_BROWN.get(), "棕色睡袋", "§c不会§r重置出生点。");
            this.addBlockWithLore(TolkienBlocks.SLEEPING_BAG_CYAN.get(), "青色睡袋", "§c不会§r重置出生点。");
            this.addBlockWithLore(TolkienBlocks.SLEEPING_BAG_GRAY.get(), "灰色睡袋", "§c不会§r重置出生点。");
            this.addBlockWithLore(TolkienBlocks.SLEEPING_BAG_GREEN.get(), "绿色睡袋", "§c不会§r重置出生点。");
            this.addBlockWithLore(TolkienBlocks.SLEEPING_BAG_LIGHT_BLUE.get(), "淡蓝色睡袋", "§c不会§r重置出生点。");
            this.addBlockWithLore(TolkienBlocks.SLEEPING_BAG_LIGHT_GRAY.get(), "淡灰色睡袋", "§c不会§r重置出生点。");
            this.addBlockWithLore(TolkienBlocks.SLEEPING_BAG_LIME.get(), "黄绿色睡袋", "§c不会§r重置出生点。");
            this.addBlockWithLore(TolkienBlocks.SLEEPING_BAG_MAGENTA.get(), "品红色睡袋", "§c不会§r重置出生点。");
            this.addBlockWithLore(TolkienBlocks.SLEEPING_BAG_ORANGE.get(), "橙色睡袋", "§c不会§r重置出生点。");
            this.addBlockWithLore(TolkienBlocks.SLEEPING_BAG_PINK.get(), "粉色睡袋", "§c不会§r重置出生点。");
            this.addBlockWithLore(TolkienBlocks.SLEEPING_BAG_PURPLE.get(), "紫色睡袋", "§c不会§r重置出生点。");
            this.addBlockWithLore(TolkienBlocks.SLEEPING_BAG_WHITE.get(), "白色睡袋", "§c不会§r重置出生点。");
            this.addBlockWithLore(TolkienBlocks.SLEEPING_BAG_YELLOW.get(), "黄色睡袋", "§c不会§r重置出生点。");

                // Screens
            this.addItemScreen(TolkienItems.BRONZE_KEY.get(), "青铜钥匙");
            this.addCodeScreen(TolkienItems.BRONZE_KEY.get(), "青铜钥匙 - 编号");
            this.addItemScreen(TolkienItems.SILVER_KEY.get(), "银钥匙");
            this.addCodeScreen(TolkienItems.SILVER_KEY.get(), "银钥匙 - 编号");
            this.addItemScreen(TolkienItems.GOLD_KEY.get(), "金钥匙");
            this.addCodeScreen(TolkienItems.GOLD_KEY.get(), "金钥匙 - 编号");
            this.addItemScreen(TolkienItems.MITHRIL_KEY.get(), "秘银钥匙");
            this.addCodeScreen(TolkienItems.MITHRIL_KEY.get(), "秘银钥匙 - 编号");
            this.addItemScreen(TolkienItems.MASTER_KEY.get(), "万能钥匙");
            this.addCodeScreen(TolkienItems.MASTER_KEY.get(), "万能钥匙 - 编号");
            this.addItemScreen(TolkienItems.COIN_POUCH.get(), "硬币袋");
            this.addItemScreen(TolkienItems.KEY_RING.get(), "钥匙扣");
            this.addBlockScreen(TolkienBlocks.TRINKET_TABLE.get(), "饰品合成");
            this.addBlockScreen(TolkienBlocks.FIREPLACE.get(), "壁炉");
            this.addBlockScreen(TolkienBlocks.PIGGYBANK.get(), "猪猪存钱罐");
            this.addBlockScreen(TolkienBlocks.BACKPACK.get(), "冒险者背包");
            this.addBlockScreen(TolkienBlocks.LOCKABLE_CHEST_BLOCK.get(), "可上锁的箱子");
            this.addBlockScreen(TolkienBlocks.LOCKABLE_TREASURE_CHEST_BLOCK.get(), "可上锁的宝箱");
            this.addBlockScreen(TolkienBlocks.LOCKABLE_DOUBLE_CHEST_BLOCK.get(), "可上锁的大箱子");
            this.addBlockScreen(TolkienBlocks.LOCKABLE_DOUBLE_TREASURE_CHEST_BLOCK.get(), "可上锁的大宝箱");
            this.addBlockScreen(TolkienBlocks.KEY_STONE_BLOCK.get(), "钥匙石方块");
            this.add("screen.tolkienmobs.namefieldtext", "确认编号");
            this.add("screen.tolkienmobs.keycodeplaceholder", "找不到编码");
            this.add("screen.tolkienmobs.keyuses", "启用后的可使用次数");
            this.add("screen.tolkienmobs.keystone.always", "用按键切换红石 - 未激活");
            this.add("screen.tolkienmobs.keystone.always.active", "用按键切换红石 - 激活");
            this.add("screen.tolkienmobs.keystone.delay", "红石保持 x 刻 - 未激活");
            this.add("screen.tolkienmobs.keystone.delay.active", "红石保持 x 刻 - 激活");
            this.add("screen.tolkienmobs.keystone.pulse", "使用按键时，红石的作用类似于按钮 - 未激活");
            this.add("screen.tolkienmobs.keystone.pulse.active", "使用按键时，红石的作用类似于按钮 - 激活");
            this.add("screen.tolkienmobs.keystone.key.consume", "当使用或被使用时获取钥匙");
            this.add("screen.tolkienmobs.keystone.key.keep", "玩家保留钥匙直至用完次数");
            this.add("screen.tolkienmobs.keystone.tickdelay", "§l** 仅限时刻延迟模式***§r 设置红石的延迟量");
            this.add("screen.tolkienmobs.backpack.bed.deployed", "铺设睡袋");
            this.add("screen.tolkienmobs.backpack.bed.remove", "收拾睡袋");
            this.add("screen.tolkienmobs.backpack.campfire.deployed", "架设营火");
            this.add("screen.tolkienmobs.backpack.campfire.remove", "收拾营火");
            this.add("screen.tolkienmobs.backpack.close.upgrade", "关闭升级窗口");
            this.add("screen.tolkienmobs.backpack.open.upgrade", "打开升级窗口");
            this.add("screen.tolkienmobs.backpack.backpack_upgrade", "升级");
            this.add("screen.tolkienmobs.backpack.fluid", "流体：");
            this.add("screen.tolkienmobs.backpack.fluid_storage", "流体储存");
            this.add("screen.tolkienmobs.camo_spawner", "刷怪笼设置");
            this.add("screen.tolkienmobs.camo_spawner.actRngeValue", "距离玩家多远距离开始激活");
            this.add("screen.tolkienmobs.camo_spawner.activationRange", "激活范围");
            this.add("screen.tolkienmobs.camo_spawner.clusterRange", "搜索范围");
            this.add("screen.tolkienmobs.camo_spawner.clusterRangeValue", "搜索生物的范围来决定是否还刷出生物");
            this.add("screen.tolkienmobs.camo_spawner.entityTags", "当前实体");
            this.add("screen.tolkienmobs.camo_spawner.ignoreSpawnReq.enabled", "生成要求 - 已启用");
            this.add("screen.tolkienmobs.camo_spawner.ignoreSpawnReq.ignored", "生成要求 - 忽略");
            this.add("screen.tolkienmobs.camo_spawner.requirePlayer.enabled", "需要玩家 - 已启用");
            this.add("screen.tolkienmobs.camo_spawner.requirePlayer.disabled", "需要玩家 - 已停用");
            this.add("screen.tolkienmobs.camo_spawner.spawnerParticles.disabled", "禁用刷怪笼粒子效果");
            this.add("screen.tolkienmobs.camo_spawner.spwnCountValue", "可生成的最大数量生物");
            this.add("screen.tolkienmobs.camo_spawner.maxCluster", "最大生成");
            this.add("screen.tolkienmobs.camo_spawner.maxClusterValue", "在附近不再出现新生物之前允许出现的生物数量");
            this.add("screen.tolkienmobs.camo_spawner.maxDelayValue", "刷怪倒计时的最大启动值");
            this.add("screen.tolkienmobs.camo_spawner.maxSpawnDelay", "最大延迟");
            this.add("screen.tolkienmobs.camo_spawner.minDelayValue", "刷怪倒计时的最小启动值");
            this.add("screen.tolkienmobs.camo_spawner.minSpawnDelay", "最小延迟");
            this.add("screen.tolkienmobs.camo_spawner.saveValue", "保存值");
            this.add("screen.tolkienmobs.camo_spawner.spawnCount", "生成数量");
            this.add("screen.tolkienmobs.camo_spawner.spawnRange", "生成范围");
            this.add("screen.tolkienmobs.camo_spawner.spawnerParticles.enabled", "启用刷怪笼粒子效果");
            this.add("screen.tolkienmobs.camo_spawner.spwnRngeValue", "生物从刷怪笼刷出的最大距离");
            this.add("screen.tolkienmobs.camo_spawner.title", "伪装的刷怪笼");
            this.add("screen.tolkienmobs.milestone", "选择你的目的地");
            this.add("screen.tolkienmobs.milestone.distance", "每 X 个方块的距离（成本为距离除以该数字）");
            this.add("screen.tolkienmobs.milestone.dimension", "跨越维度的成本乘数");
            this.add("screen.tolkienmobs.milestone.instructions", "设置该里程碑的名称");

                // Buttons
            this.add("buttons.tolkienmobs.saveinfo", "保存信息");
            this.add("buttons.tolkienmobs.milestone.saveinfo", "保存");

                // Fluid Tooltips
            this.add("tolkienmobs.tooltip.liquid.amount.empty", "储罐空");
            this.add("tolkienmobs.tooltip.liquid.amount.with.capacity", "%s / %s mB");
            this.add("tolkienmobs.tooltip.liquid.amount", "%s mB");
            this.add("tolkienmobs.camo_fluid.fluid.instructions", "将流体桶放入槽中");

                // Miscellaneous Tooltips
            this.add("tooltip.tolkienmobs.ranged.power", " %sx 击中威力");
            this.add("tooltip.tolkienmobs.bow_speed.faster", " %sx 更快提升");
            this.add("tooltip.tolkienmobs.bow_speed.slower", " %sx 更慢提升");
            this.add("tooltip.tolkienmobs.ammo.infinite", "无限");
            this.add("tooltip.tolkienmobs.damage.base", "%s 基础伤害");
            this.add("tooltip.tolkienmobs.fuel.remaining", "%s 剩余燃料（最多 16000）");
            this.add("tooltip.tolkienmobs.milestone.payment_method", "付款方式 - %s");

                // Potions & Effects
                    // Beneficial
            this.createPotionSet("personal_blacksmith", "随身铁匠");
            this.createPotionSet("ent_draught", "恩特饮料");
            this.createPotionSet("blessing_of_eru", "一如祝福");
            this.createPotionSet("elf_vitality", "精灵长寿");
            this.createPotionSet("elven_nimbleness", "精灵敏捷");

                    // Harmful
            this.createPotionSet("elemental_flight", "重力飞行");
            this.createPotionSet("elemental_drowning", "深海溺水");
            this.createPotionSet("elemental_lightning", "天打雷劈");
            this.createPotionSet("elemental_burning", "烈焰焚身");
            this.createPotionSet("sleepnesia", "失眠");
            this.createPotionSet("inventory_corrosion", "腐蚀");
            this.createPotionSet("dread_aura", "强烈悚怖");
            this.createPotionSet("crippling_terror", "致命恐惧");

                // Sounds
            this.addSound("block", "chest_open", "箱子：开启");
            this.addSound("block", "chest_close", "箱子：关闭");
            this.addSound("block", "cathedralbell", "钟声：敲响");
            this.addSound("block", "locust_ambient", "蚱蜢：窸窸窣窣");
            this.addSound("block", "lightningbug_ambient", "萤火虫：咕咕作响");
            this.addSound("ambient", "medievalseaport", "大海：涛声鸟鸣");
            this.addSound("ambient", "medievaltavern", "小酒馆的顾客：叽叽喳喳");
            this.addSound("ambient", "medievalcitymarket", "市集：车水马龙");
            this.addSound("ambient", "medievalcity", "城市：熙熙攘攘");
            this.addSound("ambient", "waterworks", "古老的机械洞穴：噪声");
            this.addSound("ambient", "underworld", "地下洞穴：毛骨悚然");
            this.addSound("ambient", "khazaddum", "古老矮人城市：回响");
            this.addSound("ambient", "pathsofthedead", "亡者之路：道路断绝 亡者守护");
            this.addSound("ambient", "arda_portal", "通往阿尔达的传送门：呼唤");
            this.addSound("item", "hype_horn", "喇叭：庆祝胜利");
            this.addSound("mob", "coin_trader", "硬币兑换商：出现");

                // Entities
                    // Villager
            this.add("entity.minecraft.villager.tolkienmobs.coin_trader", "硬币兑换商");
            this.add("entity.minecraft.villager.tolkienmobs.grocery_store", "杂货店");
            this.add("entity.minecraft.villager.tolkienmobs.pet_merchant", "废品处理商");
            this.add("entity.minecraft.villager.tolkienmobs.junk_trader", "宠物商人");
            this.add("entity.minecraft.villager.tolkienmobs.trinket_smith", "魔法盔甲匠");
            this.add("entity.minecraft.villager.tolkienmobs.trinket_tailor", "魔法裁缝");

                    //Ambient
            this.add(TolkienEntities.ENTITY_TTM_GECKO.get(), "壁虎");
            this.add(TolkienEntities.EGG_TTMGECKO.get(), "壁虎刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_RAT.get(), "老鼠");
            this.add(TolkienEntities.EGG_TTMRAT.get(), "老鼠刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_SQUIRREL.get(), "松鼠");
            this.add("entity.tolkienmobs.entityttmsquirrel.killer_squirrel", "§4杀手松鼠§r");
            this.add(TolkienEntities.EGG_TTMSQUIRREL.get(), "松鼠刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_FROG.get(), "青蛙");
            this.add("entity.tolkienmobs.entityttmfrog.murder_frog", "§4杀人蛙§r");
            this.add(TolkienEntities.EGG_TTMFROG.get(), "青蛙刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_THRUSH.get(), "鸫鸟");
            this.add(TolkienEntities.EGG_TTMTHRUSH.get(), "鸫鸟刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_CREBAIN.get(), "克拉班");
            this.add(TolkienEntities.EGG_TTMCREBAIN.get(), "克拉班刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_SWARM.get(), "蠓蝇");
            this.add(TolkienEntities.EGG_TTMSWARM.get(), "蠓蝇刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_GREAT_EAGLE.get(), "鹰王");
            this.add(TolkienEntities.EGG_TTMGREATEAGLE.get(), "鹰王刷怪蛋");

                    // Passive
            this.add(TolkienEntities.ENTITY_TTM_AUROCH.get(), "野牛");
            this.add(TolkienEntities.EGG_TTMAUROCH.get(), "野牛刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_MUMAKIL.get(), "猛犸");
            this.add(TolkienEntities.EGG_TTMMUMAKIL.get(), "猛犸刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_GOAT.get(), "战争公羊");
            this.add(TolkienEntities.EGG_TTMGOAT.get(), "战争公羊刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_NAZGULSTEED.get(), "那兹古尔黑骏马");
            this.add(TolkienEntities.EGG_TTMNAZGULSTEED.get(), "那兹古尔黑骏马刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_SHADOWFAX.get(), "捷影");
            this.add(TolkienEntities.EGG_TTMSHADOWFAX.get(), "捷影刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_GOLLUM.get(), "咕噜");
            this.add(TolkienEntities.EGG_TTMGOLLUM.get(), "咕噜刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_ISTARI.get(), "伊斯塔尔");
            this.add(TolkienEntities.EGG_TTMISTARI.get(), "伊斯塔尔刷怪蛋");

                    // NPC
            this.addVillager(TolkienEntities.ENTITY_TTM_HUMAN.get(), "人类");
            this.add(TolkienEntities.EGG_TTMHUMAN.get(), "人类刷怪蛋");
            this.addVillager(TolkienEntities.ENTITY_TTM_DWARF.get(), "矮人");
            this.add(TolkienEntities.EGG_TTMDWARF.get(), "矮人刷怪蛋");
            this.addVillager(TolkienEntities.ENTITY_TTM_ELVES.get(), "精灵");
            this.add(TolkienEntities.EGG_TTMELVES.get(), "精灵刷怪蛋");
            this.addVillager(TolkienEntities.ENTITY_TTM_HOBBIT.get(), "霍比特人");
            this.add(TolkienEntities.EGG_TTMHOBBIT.get(), "霍比特人刷怪蛋");
            this.addVillager(TolkienEntities.ENTITY_TTM_SOUTHRON.get(), "南蛮子");
            this.add(TolkienEntities.EGG_TTMSOUTHRON.get(), "南蛮子刷怪蛋");
            this.addVillager(TolkienEntities.ENTITY_TTM_ORC_TRADER.get(), "奥克商人");
            this.add(TolkienEntities.EGG_TTMORC_TRADER.get(), "奥克商人刷怪蛋");

                    //Monster
            this.add(TolkienEntities.ENTITY_TTM_BARROW.get(), "古冢尸妖");
            this.add(TolkienEntities.EGG_TTMBARROW.get(), "古冢尸妖刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_OATHBREAKER.get(), "背誓者（山中之民）");
            this.add(TolkienEntities.EGG_TTMOATHBREAKER.get(), "背誓者刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_FELLSPIRIT.get(), "堕落神灵");
            this.add(TolkienEntities.ENTITY_TTM_ENRAGED_FELLSPIRIT.get(), "§4愤怒的堕落之灵§r");
            this.add(TolkienEntities.EGG_TTMFELLSPIRIT.get(), "堕落神灵刷怪蛋");
            this.add(TolkienEntities.EGG_TTMENRAGEDFELLSPIRIT.get(), "愤怒的堕落之灵刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_BRIGAND.get(), "土匪");
            this.add(TolkienEntities.EGG_TTMBRIGAND.get(), "土匪刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_HARADRIM.get(), "哈拉德人");
            this.add(TolkienEntities.EGG_TTMHARADRIM.get(), "哈拉德人刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_ROMIEWALKER.get(), "希望行者");
            this.add(TolkienEntities.EGG_TTMROMIEWALKER.get(), "希望行者刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_MIMICCHEST.get(), "宝箱怪");
            this.add(TolkienEntities.EGG_TTMMIMICCHEST.get(), "宝箱怪刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_MORDORORC.get(), "魔多奥克");
            this.add(TolkienEntities.EGG_TTMMORDORORC.get(), "魔多奥克刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_URUKHAI.get(), "乌鲁克族");
            this.add(TolkienEntities.EGG_TTMURUKHAI.get(), "乌鲁克族刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_DUERGAR.get(), "杜尔加矮人");
            this.add(TolkienEntities.EGG_TTMDUERGAR.get(), "杜尔加矮人刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_GOBLIN.get(), "半兽人");
            this.add(TolkienEntities.EGG_TTMGOBLIN.get(), "半兽人刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_MIRKWOODSPIDER.get(), "黑森林蜘蛛");
            this.add(TolkienEntities.EGG_TTMMIRKWOODSPIDER.get(), "黑森林蜘蛛刷怪蛋");
            this.add(TolkienEntities.ENTITY_ROCKGOLEM.get(), "岩石魔像");
            this.add(TolkienEntities.EGG_TTMROCKGOLEM.get(), "岩石魔像刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_HURON.get(), "胡奥恩");
            this.add(TolkienEntities.EGG_TTMHURON.get(), "胡奥恩刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_MINOTAUR.get(), "牛头人");
            this.add(TolkienEntities.EGG_TTMMINOTAUR.get(), "牛头人刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_DEEPCLAW.get(), "深爪");
            this.add(TolkienEntities.EGG_TTMDEEPCLAW.get(), "深爪刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_TROLL.get(), "洞穴食人妖");
            this.add(TolkienEntities.EGG_TTMTROLL.get(), "洞穴食人妖刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_TREEENT.get(), "恩特树人");
            this.add(TolkienEntities.EGG_TTMTREEENT.get(), "恩特树人刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_SWAMPHAG.get(), "沼泽女巫");
            this.add(TolkienEntities.EGG_TTMSWAMPHAG.get(), "沼泽女巫刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_WARG.get(), "座狼");
            this.add(TolkienEntities.EGG_TTMWARG.get(), "座狼刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_ELEMENTALGOLEM.get(), "元素魔像");
            this.add(TolkienEntities.EGG_TTMELEMENTALGOLEM.get(), "元素魔像刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_NAZGUL.get(), "那兹古尔（戒灵）");
            this.add(TolkienEntities.EGG_TTMNAZGUL.get(), "那兹古尔刷怪蛋");

                    // Boss
            this.add(TolkienEntities.ENTITY_TTM_GOBLINKING.get(), "半兽人之王");
            this.add(TolkienEntities.EGG_TTMGOBLINKING.get(), "半兽人之王刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_BALROG.get(), "炎魔");
            this.add(TolkienEntities.EGG_TTMBALROG.get(), "炎魔刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_SHELOB.get(), "希洛布");
            this.add(TolkienEntities.EGG_TTMSHELOB.get(), "希洛布刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_WITCHKING.get(), "安格玛巫王");
            this.add(TolkienEntities.EGG_TTMWITCHKING.get(), "巫王刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_WATCHER.get(), "水中监视者");
            this.add(TolkienEntities.EGG_TTMWATCHER.get(), "监视者刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_MITHRILGOLEM.get(), "秘银魔像");
            this.add(TolkienEntities.EGG_TTMMITHRILGOLEM.get(), "秘银魔像刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_MORGULIRONGOLEM.get(), "魔古尔铁魔像");
            this.add(TolkienEntities.EGG_TTMMORGULIRONGOLEM.get(), "魔古尔铁魔像刷怪蛋");
            this.add(TolkienEntities.ENTITY_TTM_GWAHIR.get(), "大鹰之王 - 格怀希尔");
            this.add(TolkienEntities.EGG_TTMGWAHIR.get(), "格怀希尔刷怪蛋");
            this.add(TolkienEntities.ENTITY_FELL_BEAST.get(), "凶恶巨兽");
            this.add(TolkienEntities.EGG_TTMFELLBEAST.get(), "凶恶巨兽刷怪蛋");

        // Enchantments
            this.addEnchantment("balrog_mark_key", "炎魔的标记");
            this.addEnchantmentDesc("balrog_mark_key", "从阴影与火焰中，大地化作滚烫的岩浆，所到之处皆是熔岩。");
            this.addEnchantment("dwarven_endurance_key", "矮人的耐力");
            this.addEnchantmentDesc("dwarven_endurance_key", "感觉没有什么能阻挡你（当然，这里指的是饥饿），总是让你饱腹。");
            this.addEnchantment("dwarven_mining_key", "矮人的采矿");
            this.addEnchantmentDesc("dwarven_mining_key", "开采矿脉中所有的匹配方块。");
            this.addEnchantment("elven_fleetfoot_key", "精灵的疾步");
            this.addEnchantmentDesc("elven_fleetfoot_key", "以精灵的速度行走。");
            this.addEnchantment("elven_longevity_key", "精灵的长寿");
            this.addEnchantmentDesc("elven_longevity_key", "精灵可以永生，你或许不能，但你一定能活得更久。");
            this.addEnchantment("gondorian_resolve_key", "刚铎人的决心");
            this.addEnchantmentDesc("gondorian_resolve_key", "你的决心让你在受到打击时不会被击倒。");
            this.addEnchantment("hobbit_plow_key", "霍比特人的犁");
            this.addEnchantmentDesc("hobbit_plow_key", "利用配备的水源会自动耕种 9x9 的区域。");
            this.add("effect.tolkienmobs.elven_nimbleness.tooltip", "步行辅助");

        // Biomes
            this.add("biome.tolkienmobs.fangorn_forest", "范贡森林");
            this.add("biome.tolkienmobs.mordor", "魔多");
            this.add("biome.tolkienmobs.ash_mountains", "埃瑞德砾苏伊");
            this.add("biome.tolkienmobs.marshes", "宁达尔夫草沼");
            this.add("biome.tolkienmobs.mirkwood", "黑森林");
            this.add("biome.tolkienmobs.mirkwood_spooky", "蜘蛛黑森林");
            this.add("biome.tolkienmobs.lorinand", "洛丝罗瑞恩");
            this.add("biome.tolkienmobs.barrow_downs", "提殒戈沙德");
            this.add("biome.tolkienmobs.shire", "夏尔");
            this.add("biome.tolkienmobs.firien", "菲瑞恩森林");
            this.add("biome.tolkienmobs.dagorlad", "褐地");
            this.add("biome.tolkienmobs.haradwaith", "哈拉德地区");
            this.add("biome.tolkienmobs.gladden", "金鸢尾沼地");
            this.add("biome.tolkienmobs.hithaeglir", "迷雾山脉");
            this.add("biome.tolkienmobs.iron_hills", "铁丘陵");
            this.add("block.tolkienmobs.hardened_leaves_mallorn", "瑁珑树叶");
            this.add("block.tolkienmobs.hardened_leaves_mirkwood", "阴郁树叶");
            this.add("block.tolkienmobs.hardened_leaves_culumalda", "库露瑁勒达树叶");
            this.add("block.tolkienmobs.hardened_leaves_lebethron", "莱贝斯隆树叶");
            this.add("block.tolkienmobs.hardened_leaves_fangornoak", "范贡橡树树叶");
            this.add("block.tolkienmobs.hardened_leaves_dwarven_maple", "矮人枫树树叶");

        // Chat Messages
            this.add("tolkienmobs.msg.helpcomming", "半兽人之王正试图寻求帮助……增援部队已经抵达！");
            this.add("tolkienmobs.msg.nohelp", "半兽人之王正试图寻求帮助，但是没有增援抵达。");
            this.add("tolkienmobs.msg.nodrown", "半兽人之王不想淹死。");
            this.add("tolkienmobs.msg.onfire", "半兽人之王正在保护自己免受火焰的伤害。");
            this.add("tolkienmobs.msg.healself", "半兽人之王受伤了，正在疗伤。");
            this.add("tolkienmobs.msg.speedup", "半兽人之王正试图赶上你的速度。");
            this.add("tolkienmobs.msg.nodrown.balrog", "炎魔不想淹死。");
            this.add("tolkienmobs.msg.onfire.balrog", "炎魔正在保护自己免受火焰的伤害。");
            this.add("tolkienmobs.msg.healself.balrog", "炎魔受伤了，正在疗伤。");
            this.add("tolkienmobs.msg.speedup.balrog", "炎魔正试图赶上你的速度。");
            this.add("tolkienmobs.msg.nodrown.gwahir", "格怀希尔不想淹死。");
            this.add("tolkienmobs.msg.onfire.gwahir", "格怀希尔正在保护自己免火焰的伤害。");
            this.add("tolkienmobs.msg.healself.gwahir", "格怀希尔受伤了，正在疗伤。");
            this.add("tolkienmobs.msg.speedup.gwahir", "格怀希尔正试图赶上你的速度。");
            this.add("tolkienmobs.msg.helpcomming.shelob", "希洛布正试图寻求帮助……增援部队已经抵达！");
            this.add("tolkienmobs.msg.nohelp.shelob", "希洛布正试图寻求帮助，但是没有增援抵达。");
            this.add("tolkienmobs.msg.nodrown.shelob", "希洛布不想淹死。");
            this.add("tolkienmobs.msg.onfire.shelob", "希洛布正在保护自己免受火焰的伤害。");
            this.add("tolkienmobs.msg.healself.shelob", "希洛布受伤了，正在疗伤。");
            this.add("tolkienmobs.msg.speedup.shelob", "希洛布正试图赶上你的速度。");
            this.add("tolkienmobs.msg.healself.watcher", "监视者受伤了，正在疗伤。");
            this.add("tolkienmobs.msg.speedup.watcher", "监视者正试图赶上你的速度。");
            this.add("tolkienmobs.msg.deploy_sleeping_bag", "有东西挡住了睡袋。");
            this.add("tolkienmobs.msg.deploy_campfire", "有东西挡住了营火。");
            this.add("tolkienmobs.msg.key_used", "钥匙没有其余的用途了。");
            this.add("tolkienmobs.msg.cleared.entities", "所有现有实体都清除了……");
            this.add("tolkienmobs.msg.added.entities", "实体已添加……");
            this.add("tolkienmobs.msg.nomore.entities", "无法添加第二个实体，第一个实体已被替换……");
            this.add("screen.tolkienmobs.camo_spawner.remove_mob", "清除所有生物");
            this.add("tolkienmobs.msg.payment", "付款项目设置为……");
            this.add("tolkienmobs.msg.payment.insufficient", "条件不足以传送！");
            this.add("tolkienmobs.msg.destination", "未发现目标");
            this.add("tolkienmobs.msg.wrong_key", "你需要正确的钥匙！");
        this.add("tolkienmobs.msg.ancient_watcher.warn", "恐惧的阴影笼罩着你，让你畏缩不前。");
        this.add("tolkienmobs.msg.ancient_watcher.safe", "压迫对你没有任何影响。");
    }

    @Nonnull
    @Override
    public String getName() {
        return "Tolkienmobs - English Language Generator";
    }
}
