package com.greatorator.tolkienmobs.datagen.loot;

import com.greatorator.tolkienmobs.datagen.helpers.TolkienLootHelper;
import com.greatorator.tolkienmobs.init.TolkienItems;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.registries.Registries;
import net.minecraft.data.loot.LootTableSubProvider;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.enchantment.Enchantment;
import net.minecraft.world.level.storage.loot.LootPool;
import net.minecraft.world.level.storage.loot.LootTable;
import net.minecraft.world.level.storage.loot.entries.LootItem;
import net.minecraft.world.level.storage.loot.functions.EnchantRandomlyFunction;
import net.minecraft.world.level.storage.loot.functions.SetItemCountFunction;
import net.minecraft.world.level.storage.loot.providers.number.UniformGenerator;

import java.util.function.BiConsumer;

public record TolkienChestLootTables(HolderLookup.Provider registries) implements LootTableSubProvider {
    @Override
    public void generate(BiConsumer<ResourceKey<LootTable>, LootTable.Builder> register) {
        HolderLookup.RegistryLookup<Enchantment> lookup = this.registries.lookupOrThrow(Registries.ENCHANTMENT);

        register.accept(TolkienLootHelper.HOBBIT_GROCER,
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(UniformGenerator.between(3, 5))
                                .setBonusRolls(UniformGenerator.between(1, 2))
                                .add(LootItem.lootTableItem(TolkienItems.FOOD_HONEY.get())
                                                .setWeight(18))
                                .add(LootItem.lootTableItem(TolkienItems.HONEY_CAKE.get())
                                        .setWeight(12)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.MUSIC_DISC_13)
                                        .setWeight(15)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.MUSIC_DISC_CAT)
                                        .setWeight(15)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 2))))
                                .add(LootItem.lootTableItem(Items.NAME_TAG)
                                        .setWeight(20)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.GOLDEN_APPLE)
                                        .setWeight(2))
                                .add(LootItem.lootTableItem(Items.BEETROOT_SEEDS)
                                        .setWeight(10)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.MELON_SEEDS)
                                        .setWeight(15))
                                .add(LootItem.lootTableItem(Items.PUMPKIN_SEEDS)
                                        .setWeight(10))));
        register.accept(TolkienLootHelper.HOBBIT_HOUSE,
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(UniformGenerator.between(3, 5))
                                .setBonusRolls(UniformGenerator.between(1, 2))
                                .add(LootItem.lootTableItem(TolkienItems.FOOD_HONEY.get())
                                        .setWeight(18))
                                .add(LootItem.lootTableItem(TolkienItems.CRAM.get())
                                        .setWeight(12)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.STONE_AXE)
                                        .setWeight(15)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.STONE_PICKAXE)
                                        .setWeight(15)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 2))))
                                .add(LootItem.lootTableItem(Items.NAME_TAG)
                                        .setWeight(20)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.APPLE)
                                        .setWeight(2))
                                .add(LootItem.lootTableItem(Items.BREAD)
                                        .setWeight(10)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.COOKED_SALMON)
                                        .setWeight(15))
                                .add(LootItem.lootTableItem(Items.COOKED_PORKCHOP)
                                        .setWeight(10))));
        register.accept(TolkienLootHelper.ELVEN_HOUSE,
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(UniformGenerator.between(3, 5))
                                .setBonusRolls(UniformGenerator.between(1, 2))
                                .add(LootItem.lootTableItem(TolkienItems.DRINK_ELF_VITALITY.get())
                                        .setWeight(18))
                                .add(LootItem.lootTableItem(TolkienItems.LEMBAS.get())
                                        .setWeight(12)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.GOLDEN_AXE)
                                        .setWeight(15)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.GOLDEN_PICKAXE)
                                        .setWeight(15)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 2))))
                                .add(LootItem.lootTableItem(Items.NAME_TAG)
                                        .setWeight(20)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.GOLDEN_APPLE)
                                        .setWeight(2))
                                .add(LootItem.lootTableItem(Items.BREAD)
                                        .setWeight(10)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.COOKED_SALMON)
                                        .setWeight(15))
                                .add(LootItem.lootTableItem(Items.BOOK)
                                        .setWeight(2)
                                        .apply(EnchantRandomlyFunction.randomApplicableEnchantment(this.registries())))
                                .add(LootItem.lootTableItem(Items.COOKED_PORKCHOP)
                                        .setWeight(10))));
        register.accept(TolkienLootHelper.DWARF_HOUSE,
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(UniformGenerator.between(3, 5))
                                .setBonusRolls(UniformGenerator.between(1, 2))
                                .add(LootItem.lootTableItem(TolkienItems.DRINK_PERSONAL_BLACKSMITH.get())
                                        .setWeight(18))
                                .add(LootItem.lootTableItem(TolkienItems.CRAM.get())
                                        .setWeight(12)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.IRON_AXE)
                                        .setWeight(15)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.IRON_PICKAXE)
                                        .setWeight(15)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 2))))
                                .add(LootItem.lootTableItem(Items.NAME_TAG)
                                        .setWeight(20)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.GOLDEN_APPLE)
                                        .setWeight(2))
                                .add(LootItem.lootTableItem(Items.BREAD)
                                        .setWeight(10)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.COOKED_SALMON)
                                        .setWeight(15))
                                .add(LootItem.lootTableItem(Items.BOOK)
                                        .setWeight(2)
                                        .apply(EnchantRandomlyFunction.randomApplicableEnchantment(this.registries())))
                                .add(LootItem.lootTableItem(Items.COOKED_PORKCHOP)
                                        .setWeight(10))));
        register.accept(TolkienLootHelper.HUMAN_HOUSE,
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(UniformGenerator.between(3, 5))
                                .setBonusRolls(UniformGenerator.between(1, 2))
                                .add(LootItem.lootTableItem(TolkienItems.GROG.get())
                                        .setWeight(18))
                                .add(LootItem.lootTableItem(TolkienItems.HONEY_CAKE.get())
                                        .setWeight(12)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.DIAMOND_AXE)
                                        .setWeight(15)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.DIAMOND_PICKAXE)
                                        .setWeight(15)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 2))))
                                .add(LootItem.lootTableItem(Items.NAME_TAG)
                                        .setWeight(20)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.GOLDEN_APPLE)
                                        .setWeight(2))
                                .add(LootItem.lootTableItem(Items.BREAD)
                                        .setWeight(10)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.COOKED_SALMON)
                                        .setWeight(15))
                                .add(LootItem.lootTableItem(Items.COOKED_PORKCHOP)
                                        .setWeight(10))));
        register.accept(TolkienLootHelper.BARROW_CHEST,
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(UniformGenerator.between(3, 5))
                                .setBonusRolls(UniformGenerator.between(1, 2))
                                .add(LootItem.lootTableItem(TolkienItems.FOOD_HONEY.get())
                                        .setWeight(18))
                                .add(LootItem.lootTableItem(TolkienItems.CRAM.get())
                                        .setWeight(12)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.BOOK)
                                        .setWeight(10)
                                        .apply(EnchantRandomlyFunction.randomApplicableEnchantment(this.registries))
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 1))))
                                .add(LootItem.lootTableItem(Items.GOLDEN_HORSE_ARMOR)
                                        .setWeight(15)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 2))))
                                .add(LootItem.lootTableItem(Items.NAME_TAG)
                                        .setWeight(20)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.MUSIC_DISC_CAT)
                                        .setWeight(2))
                                .add(LootItem.lootTableItem(Items.MUSIC_DISC_13)
                                        .setWeight(10)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.GOLDEN_APPLE)
                                        .setWeight(15))
                                .add(LootItem.lootTableItem(Items.SADDLE)
                                        .setWeight(10))));
        register.accept(TolkienLootHelper.BARROW_GRAVE,
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(UniformGenerator.between(3, 5))
                                .setBonusRolls(UniformGenerator.between(1, 2))
                                .add(LootItem.lootTableItem(TolkienItems.FOOD_HONEY.get())
                                        .setWeight(18))
                                .add(LootItem.lootTableItem(Items.ROTTEN_FLESH)
                                        .setWeight(12)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7))))
                                .add(LootItem.lootTableItem(Items.BOOK)
                                        .setWeight(10)
                                        .apply(EnchantRandomlyFunction.randomApplicableEnchantment(this.registries))
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 1))))
                                .add(LootItem.lootTableItem(Items.BONE)
                                        .setWeight(15)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(4, 8))))
                                .add(LootItem.lootTableItem(Items.EMERALD)
                                        .setWeight(20)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.GOLD_INGOT)
                                        .setWeight(2))
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3)))
                                .add(LootItem.lootTableItem(Items.IRON_INGOT)
                                        .setWeight(10)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.GOLDEN_APPLE)
                                        .setWeight(15))
                                .add(LootItem.lootTableItem(Items.DIAMOND)
                                        .setWeight(10))
                                .add(LootItem.lootTableItem(Items.BOOK)
                                        .setWeight(2)
                                        .apply(EnchantRandomlyFunction.randomApplicableEnchantment(this.registries())))
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3)))));
        register.accept(TolkienLootHelper.DESOLATE_RUINS,
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(UniformGenerator.between(3, 5))
                                .setBonusRolls(UniformGenerator.between(1, 2))
                                .add(LootItem.lootTableItem(Items.DIAMOND)
                                        .setWeight(18)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7))))
                                .add(LootItem.lootTableItem(Items.IRON_INGOT)
                                        .setWeight(12)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5))))
                                .add(LootItem.lootTableItem(Items.BOOK)
                                        .setWeight(10)
                                        .apply(EnchantRandomlyFunction.randomApplicableEnchantment(this.registries))
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 1))))
                                .add(LootItem.lootTableItem(Items.BONE)
                                        .setWeight(15)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(4, 6))))
                                .add(LootItem.lootTableItem(Items.EMERALD)
                                        .setWeight(20)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.GOLD_INGOT)
                                        .setWeight(2))
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(2, 7)))
                                .add(LootItem.lootTableItem(Items.ROTTEN_FLESH)
                                        .setWeight(10)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7))))
                                .add(LootItem.lootTableItem(Items.SADDLE)
                                        .setWeight(15))
                                .add(LootItem.lootTableItem(Items.GOLDEN_HORSE_ARMOR)
                                        .setWeight(15))
                                .add(LootItem.lootTableItem(Items.DIAMOND_HORSE_ARMOR)
                                        .setWeight(15))
                                .add(LootItem.lootTableItem(Items.IRON_HORSE_ARMOR)
                                        .setWeight(15))));
        register.accept(TolkienLootHelper.SWAMP_HAG_HUT,
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(UniformGenerator.between(3, 5))
                                .setBonusRolls(UniformGenerator.between(1, 2))
                                .add(LootItem.lootTableItem(TolkienItems.ITEM_COIN_BRONZE.get())
                                        .setWeight(18)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5))))
                                .add(LootItem.lootTableItem(TolkienItems.MONSTER_FLESH.get())
                                        .setWeight(12)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.ENDER_PEARL)
                                        .setWeight(15)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.GLASS_BOTTLE)
                                        .setWeight(15)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 2))))
                                .add(LootItem.lootTableItem(Items.SPIDER_EYE)
                                        .setWeight(20)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.GUNPOWDER)
                                        .setWeight(2)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.GLOWSTONE_DUST)
                                        .setWeight(10)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.REDSTONE)
                                        .setWeight(15)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.BLAZE_POWDER)
                                        .setWeight(10)))
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))));
        register.accept(TolkienLootHelper.SPIDER_TREE,
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(UniformGenerator.between(3, 5))
                                .setBonusRolls(UniformGenerator.between(1, 2))
                                .add(LootItem.lootTableItem(TolkienItems.ITEM_COIN_BRONZE.get())
                                        .setWeight(18)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5))))
                                .add(LootItem.lootTableItem(TolkienItems.MONSTER_FLESH.get())
                                        .setWeight(12)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.ENDER_PEARL)
                                        .setWeight(15)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.GLASS_BOTTLE)
                                        .setWeight(15)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 2))))
                                .add(LootItem.lootTableItem(Items.SPIDER_EYE)
                                        .setWeight(20)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.GUNPOWDER)
                                        .setWeight(2)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.GLOWSTONE_DUST)
                                        .setWeight(10)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.REDSTONE)
                                        .setWeight(15)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.BLAZE_POWDER)
                                        .setWeight(10)))
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))));
        register.accept(TolkienLootHelper.WARG_PIT,
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(UniformGenerator.between(3, 5))
                                .setBonusRolls(UniformGenerator.between(1, 2))
                                .add(LootItem.lootTableItem(TolkienItems.ITEM_COIN_BRONZE.get())
                                        .setWeight(18)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5))))
                                .add(LootItem.lootTableItem(TolkienItems.MONSTER_FLESH.get())
                                        .setWeight(12)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.BONE)
                                        .setWeight(15)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.NAME_TAG)
                                        .setWeight(15)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 2))))
                                .add(LootItem.lootTableItem(Items.GOLD_INGOT)
                                        .setWeight(20)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(TolkienItems.INGOT_MORGULIRON.get())
                                        .setWeight(2)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2, 8))))
                                .add(LootItem.lootTableItem(TolkienItems.GROG.get())
                                        .setWeight(10)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(TolkienItems.CRAM.get())
                                        .setWeight(15)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(TolkienItems.ITEM_COIN_SILVER.get())
                                        .setWeight(10)))
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))));
        register.accept(TolkienLootHelper.MINOTAUR_CHEST,
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(UniformGenerator.between(3, 5))
                                .setBonusRolls(UniformGenerator.between(1, 2))
                                .add(LootItem.lootTableItem(TolkienItems.ITEM_COIN_SILVER.get())
                                        .setWeight(18)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5))))
                                .add(LootItem.lootTableItem(TolkienItems.MONSTER_FLESH.get())
                                        .setWeight(12)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.BONE)
                                        .setWeight(15)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(TolkienItems.ITEM_COIN_GOLD.get())
                                        .setWeight(15)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 1))))
                                .add(LootItem.lootTableItem(Items.GOLD_INGOT)
                                        .setWeight(20)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(TolkienItems.INGOT_MORGULIRON.get())
                                        .setWeight(2)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2, 8))))
                                .add(LootItem.lootTableItem(TolkienItems.GROG.get())
                                        .setWeight(10)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(TolkienItems.CRAM.get())
                                        .setWeight(15)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(TolkienItems.INGOT_MITHRIL.get())
                                        .setWeight(10))
                                .add(LootItem.lootTableItem(Items.BOOK)
                                        .setWeight(2)
                                        .apply(EnchantRandomlyFunction.randomApplicableEnchantment(this.registries())))
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3)))));
        register.accept(TolkienLootHelper.MAZE_CHEST,
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(UniformGenerator.between(3, 5))
                                .setBonusRolls(UniformGenerator.between(1, 1))
                                .add(LootItem.lootTableItem(TolkienItems.DRINK_PERSONAL_BLACKSMITH.get())
                                        .setWeight(18)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 1))))
                                .add(LootItem.lootTableItem(TolkienItems.MONSTER_FLESH.get())
                                        .setWeight(12)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.BONE)
                                        .setWeight(15)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(TolkienItems.DRINK_ENT_DRAUGHT.get())
                                        .setWeight(15)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 1))))
                                .add(LootItem.lootTableItem(TolkienItems.GEM_AMMOLITE.get())
                                        .setWeight(20)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(TolkienItems.INGOT_MORGULIRON.get())
                                        .setWeight(2)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2, 8))))
                                .add(LootItem.lootTableItem(TolkienItems.GROG.get())
                                        .setWeight(10)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(TolkienItems.CRAM.get())
                                        .setWeight(15)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(TolkienItems.INGOT_MITHRIL.get())
                                        .setWeight(10)))
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))));
        register.accept(TolkienLootHelper.GOLLUM_CAVE,
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(UniformGenerator.between(3, 5))
                                .setBonusRolls(UniformGenerator.between(1, 2))
                                .add(LootItem.lootTableItem(TolkienItems.GROG.get())
                                        .setWeight(18))
                                .add(LootItem.lootTableItem(TolkienItems.CRAM.get())
                                        .setWeight(12)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.SALMON)
                                        .setWeight(15)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.PUFFERFISH)
                                        .setWeight(15)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 2))))
                                .add(LootItem.lootTableItem(Items.COD)
                                        .setWeight(20)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.TROPICAL_FISH)
                                        .setWeight(2)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(TolkienItems.MONSTER_FLESH.get())
                                        .setWeight(10)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.GOLD_NUGGET)
                                        .setWeight(15)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 7))))
                                .add(LootItem.lootTableItem(TolkienItems.ITEM_COIN_GOLD.get())
                                        .setWeight(10)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))));
        register.accept(TolkienLootHelper.TOWER_RUINS,
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(UniformGenerator.between(3, 5))
                                .setBonusRolls(UniformGenerator.between(1, 2))
                                .add(LootItem.lootTableItem(TolkienItems.GROG.get())
                                        .setWeight(18))
                                .add(LootItem.lootTableItem(TolkienItems.CRAM.get())
                                        .setWeight(12)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.NAME_TAG)
                                        .setWeight(15)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(Items.COOKIE)
                                        .setWeight(15)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 2))))
                                .add(LootItem.lootTableItem(Items.GOLDEN_APPLE)
                                        .setWeight(20)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 1))))
                                .add(LootItem.lootTableItem(Items.ENCHANTED_GOLDEN_APPLE)
                                        .setWeight(2)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 1))))
                                .add(LootItem.lootTableItem(TolkienItems.MONSTER_FLESH.get())
                                        .setWeight(10)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))
                                .add(LootItem.lootTableItem(TolkienItems.NUGGET_MORGULIRON.get())
                                        .setWeight(15)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 7))))
                                .add(LootItem.lootTableItem(TolkienItems.ITEM_COIN_GOLD.get())
                                        .setWeight(10)
                                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3))))));
    }
}
